### ISSUE TITLE
EPI Compiler

### ISSUE THREAD

**Issue by ashriram** [RALC88/riscv-vectorized-benchmark-suite#1]
The makefiles here assume that the epi compiler is set up. Can you provide instructions on how to set it up

**Comment by RALC88** [comment]
Did you get to set it up? If you got the vector compiler 0.7 from the link I shared with you, the only step is to export the path :
export LLVM=your/path/for/epi-toolchain
export PATH=$PATH:$LLVM/bin

**Comment by ashriram** [comment]
Yes; I did. All checks out
