### ISSUE TITLE
Benchmarks not working with 1.0 branch

### ISSUE THREAD

**Issue by ashriram** [RALC88/riscv-vectorized-benchmark-suite#3]
Benchmarks currently known to be not working with 1.0 branch with CAS LLVM Compiler and Spike
canneal
jacobi-2d
particle filter
swaptions

Errors related to stores and mmap.

**Comment by ChunyuLiao** [comment]
canneal, particle, filterswaptions:
I updated the compiler. You can try again.

jacobi-2d:
Sorry, I haven't tested it.  Please refer to https://github.com/RALC88/riscv-vectorized-benchmark-suite/tree/rvv-1.0#pakage-structure  for specific passed test cases.

**Comment by ashriram** [comment]
Confirming; all working with https://github.com/isrc-cas/rvv-llvm/commit/5f23b7d7fb017b3c1011db27e7163019442264e7
