### ISSUE TITLE
ERR_CHK macro

### ISSUE THREAD

**Issue by ArdxWe** [RALC88/riscv-vectorized-benchmark-suite#5]
_blackscholes/src/blackscholes.cpp

```
#ifdef ERR_CHK
    printf("Num Errors: %d\n", numError);
#endif
```
Can I define `ERR_CHK` macro at the beginning of the source code and expect the error to be equal to 0?

```
#define ERR_CHK
// RISC-V VECTOR Version by Cristóbal Ramírez Lazo, "Barcelona 2019"
...
```
branch: rvv-1.0

**Comment by RALC88** [comment]
Hi, you will see some small differences in the final result, since we have vectorized the math functions (exp,log,etc). Then, the error will not be equal to 0.
