### ISSUE TITLE
clang-12: error: unknown argument: '-mepi' and src/utils.c:1:10: fatal error: 'math.h' file not found

### ISSUE THREAD

**Issue by Kuntin555** [RALC88/riscv-vectorized-benchmark-suite#6]
when I use llvm from PLTC （https://github.com/plctlab/llvm-project） compile the RVV benchmark（https://github.com/RALC88/riscv-vectorized-benchmark-suite/tree/rvv-1.0）
it can't find argument '-mepi'.
My steps are as follows：

compile and install the llvm
export RISCV=~/opt/riscv-vector
git clone https://github.com/plctlab/llvm-project.git
cd llvm-project-rvv-iscas
mkdir build
cd build
cmake -G "Unix Makefiles"
-DLLVM_TARGETS_TO_BUILD="RISCV"
-DCMAKE_INSTALL_PREFIX=$RISCV
-DCMAKE_BUILD_TYPE=Release
-DLLVM_USE_LINKER=gold
-DLLVM_ENABLE_PROJECTS="clang;libcxx;libcxxabi;lld" ../llvm
make -j12
make install
compile the rvv benchmark
git clone https://github.com/RALC88/riscv-vectorized-benchmark-suite.git
cd riscv-vectorized-benchmark-suite
export LLVM=/opt/riscv-vector
export PATH=$PATH:/opt/riscv-vector/bin
make all

The following error is generated during the compilation process：
xxx/bin/clang --target=riscv64-unknown-elf -march=rv64g  -O2 -c -o src/utils.o src/utils.c
src/utils.c:1:10: fatal error: 'math.h' file not found
clang-12: error: unknown argument: '-mepi'

**Comment by RALC88** [comment]
Solved

**Comment by KKKHHHLLL** [comment]
Hello, I met the same problem when compiling _jacobi-2d of the RVV benchmark. I tried on both master and rvv-1.0 branches, and the llvm tool from PLCT is on rvv-isacs branch. How can I solve the problem?

**Comment by LiamPeng** [comment]
Same problem here: clang-12: error: unknown argument: '-mepi'
How can I solve the problem?
