### ISSUE TITLE
[Question] Repository status

### ISSUE THREAD

**Issue by Incarnation-p-lee** [RALC88/riscv-vectorized-benchmark-suite#8]
Looks like quite a long time since the last update of this repository. It looks a little bit out of date. I have tried one of the benchmarks, looks like the intrinsic API has sorts of changes according to `gnu toolchain` and `llvm`. Could you please help to insight me the support status of this repository, especially for the RVV 1.0 branch?

Thanks a lot.

**Comment by ChunyuLiao** [comment]
Yes, The RVV1.0 branch have not been updated for a long time. However, RVV intrinsics are still being updated and will be considered when they are ratified. 
It may be necessary to update a version according to the RVV intrinsics doc (https://github.com/riscv-non-isa/rvv-intrinsic-doc), 
it is recommended to use the llvm-project main branch (https://github.com/llvm/llvm-project)

**Comment by Incarnation-p-lee** [comment]
Thank you for your information.

Do you think this repo is good enough for vectorization performance evaluation? If so, we can make it work well with upstream llvm.

Or is there any other candidate benchmark for the vectorization?

**Comment by ChunyuLiao** [comment]
Opencv also uses a lot of rvv intrinsics. But I don't know the link.

**Comment by Incarnation-p-lee** [comment]
I see. Thank you! But I still consider this repository can be a good start for vectorization, ;)!

**Comment by Incarnation-p-lee** [comment]
Sorry for disturbing, is there any plan to catch up with the ratified or we are waiting for ratified intrinsic?
