### ISSUE TITLE
:bug: Vectorized lavaMD bug?

### ISSUE THREAD

**Issue by mp-17** [RALC88/riscv-vectorized-benchmark-suite#9]
Hello everyone,

First of all, thanks for your great job! :-)

I am working on a custom implementation of the RiVEC benchmark suite to be run on `spike` and our vector processor Ara (https://github.com/pulp-platform/ara).

I was porting `lavaMD`, and I found an issue: 

**Preamble**:
The scalar kernel is updating multiple times the same memory location `fA[i].v`, for `0 <= i < NUMBER_PAR_PER_BOX`, within the same box (i.e., `j` is constant). 
The `fA` pointer changes its base value only when the variable `j` changes; for the rest of the time, it points to the same address (i.e., `fA` remains constant when operating within the same box). 
Since for different `k` (neighbours) and same `j` (box), the `i` assumes every value in the range `0 <= i < NUMBER_PAR_PER_BOX` multiple times, then each `fA[i].v` is an accumulator. This is also valid for the `.x`, `.y`, and `.z` components.
https://github.com/RALC88/riscv-vectorized-benchmark-suite/blob/master/_lavaMD/kernel/kernel_cpu.c#L183

**Issue**:
In the vector version instead, each `fA[i].v` does not behave as an accumulator. For example, with `i == 0`, `fA[0].v` is written with a vector store `1+box[l].nn` times, but the previous value is never read back to be accumulated. 
When `k` changes and `i` starts its sweep again from `0`, the scalar accumulators for the reductions are zeroed as well. 
https://github.com/RALC88/riscv-vectorized-benchmark-suite/blob/master/_lavaMD/kernel/kernel_vector.c#L201

Therefore, the value in memory is never accumulated, but only overwritten.
https://github.com/RALC88/riscv-vectorized-benchmark-suite/blob/master/_lavaMD/kernel/kernel_vector.c#L258

**Example**:
Let's suppose that we have only one box, so `l == 0` always. 
When `k == 0`, we will have sweep with `i` and `j`.
When `i == 0`, we sweep on `j`, and then we store `fA[0].v`, accumulating all the different contributions from the `j` sweep.
`i` Will also sweep until the end, and we will save to memory all the `fA[i].v`, accumulating each contribution from the `j` sweeps.

Up to here, both the scalar and the vector programs work correctly.

Then, `k == 1`. At this point, we should repeat everything, and we only change `rB` and `qB` base addresses. 
`fA`, instead, keeps pointing to the same location as before.
Therefore, we will sweep on `i` and `j`, and when `i == 0`, for example, we will need to accumulate again on `fA[0].v`, starting from its last value in memory. 

The vector program does not do it, and just overwrite the values in memory, without accumulating when `k` changes.

I found the problem when I checked with Spike if the scalar and vector versions of `lavaMD` could produce the same results. 
They could not, from my side. Have you tried to check if the results are the same?  

An easy fix would be https://github.com/pulp-platform/ara/pull/166/commits/89215a1a169beb80cbb30d26825ffc12c871906b

Thanks a lot,
Matteo

**Comment by RALC88** [comment]
Dear Matteo,
Thanks for reporting the bug and proposing a fix for it. I looked at fix and looks ok. Could you please create a PR for this fix?
Thank you very much !!
Cristobal RL

**Comment by mp-17** [comment]
Dear Cristobal RL, 

Sure, I will do it today! 

Best,
Matteo

EDIT: https://github.com/RALC88/riscv-vectorized-benchmark-suite/pull/10
